# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUWbdJYU6Ij4k8MkTWsG9S0Y-OQeU8n3
"""



import os

video_path = "/content/video6.mp4"
output_dir = "frames/video6"
os.makedirs(output_dir, exist_ok=True)

# Extract 1 frame per second
cmd = f"ffmpeg -i {video_path} -vf fps=3 {output_dir}/frame_%03d.jpg"
os.system(cmd)

"""# New Section"""

import shutil

# Zip the folder
shutil.make_archive('frames', 'zip', 'frames')

from google.colab import files

# Download the zip file to your computer
files.download('frames.zip')

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

import os

frame_dir = "/content/frames/video1"
frame_files = sorted(os.listdir(frame_dir))

labeled_data = []

for i, frame_name in enumerate(frame_files):
    img_path = os.path.join(frame_dir, frame_name)
    img = mpimg.imread(img_path)

    plt.imshow(img)
    plt.title(f"Click on the center of the object in {frame_name}")
    coords = plt.ginput(1)[0]  # waits for 1 click
    plt.close()

    labeled_data.append((i+1, int(coords[0]), int(coords[1])))

import pandas as pd
df = pd.DataFrame(labeled_data, columns=["Frame", "X", "Y"])
df.to_csv("labels/video1_labels.csv", index=False)

print("✅ Saved labels to video1_labels.csv")